version: '3.4'

services:
  webapi:
    build: ./WebApi
      #context: ./
      #dockerfile: ./WebApi/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      rabbitmq: 
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - 15672:15672
      - 5672:5672
    healthcheck:
      test: rabbitmq-diagnostics -q check_running && rabbitmq-diagnostics -q check_local_alarms
      interval: 5s
      timeout: 5s
      retries: 5
    environment: 
      - RABBITMQ_DEFAULT_USER=jason
      - RABBITMQ_DEFAULT_PASS=bourne

  africa_receiver:
    build: ./AfricaReceiver
      #context: ./
      #dockerfile: ./AfricaReceiver/Dockerfile
    depends_on: 
      rabbitmq: 
        condition: service_healthy
    stdin_open: true

  na_receiver:
    build: ./NorthAmericaReceiver
      #context: ./
      #dockerfile: ./NorthAmericaReceiver/Dockerfile
    depends_on: 
      rabbitmq: 
        condition: service_healthy
    stdin_open: true
