version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - ":15672"
    environment:
      RABBITMQ_DEFAULT_USER: jason
      RABBITMQ_DEFAULT_PASS: bourne

  api:
    #image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - ":80"

  get1:
    build:
      context: .
      dockerfile: OrdersReceiver/Dockerfile
    command: ["new"]
  get2:
    build:
      context: .
      dockerfile: OrdersReceiver/Dockerfile
    command: ["complete"]
  get3:
    build:
      context: .
      dockerfile: OrdersReceiver/Dockerfile
    command: ["processing"]
  get4:
    build:
      context: .
      dockerfile: ContinentsReceiver/Dockerfile
    command: ["NA"]

  


